# Configuration file for Capacitance Landau Fan in MLG.
# Top Gate fixed

file:
  data_dir: HZS63
  file_name: Cpen_LandauFan_PP
  comment: Rox=340

measurement: Cpen

Cpen:
  v1: V_tg [V]
  v2: V_sample [V]
  ch1: 0
  ch2: 1
  read1: 0
  read2: 1
  fixed: vb

Csym:
  v1: V_tg [V]
  v2: V_bg [V]
  ch1: 0
  ch2: 1
  read1: 0
  read2: 1
  fixed: vs

lockin: SR830  # Write 'SR830' or '7820'

lockin_settings:
  tc: 0.003
  acgain: 14
  sensitiviy: 5.0e-3

balancing_settings:
  balance_tc: 0.001
  n0: 0.3
  p0: 0
  tolerance: 0.005e-3
  ref_ch: 2
  offset:
    - -0.0
    - 0.0
  iter: 5
  rebalance: True

acbox_settings:
  chX1: 1.0
  chX2: 1.0
  chY1: 0.75
  chY2: 0.75
  frequency: 83564.41
  ref_atten: 23
  sample_atten: 30

dacadc_settings:
  ch1_offset: -0.0024784313
  ch2_offset: -0.0043156862

meas_parameters:
  n0_pnts: 1100
  b_pnts: 331
  n0_rng:
    - 8.1
    - 10.65
  b_rng:
    - 45
    - 12
  p0fixed: -2.0
  delta_var: -0.028
  bscale: True
  zOffset: 0.0
  scalefactor: 1.0

plot: True
