# Configuration file for Capacitance Landau Fan in MLG.
# Top Gate fixed

file:
  data_dir: TDW072821
  file_name: Ct_29K_npbridge
  comment: balanced at n = p = 0. .1 V on bias on the transistor, turning delta down from 0.5 to 0.46

measurement: Cpen

Cpen:
  v1: V_bg [V]
  v2: V_sample [V]
  ch1: 0
  ch2: 1
  read1: 1
  read2: 0
  fixed: vt

Csym:
  v1: V_tg [V]
  v2: V_bg [V]
  ch1: 1
  ch2: 0
  read1: 0
  read2: 1
  fixed: vs

lockin: SR830  # Write 'SR830' or '7280'

lockin_settings:
  tc: 8
  acgain: 14
  sensitiviy: 15

balancing_settings:
  balance_tc: 9
  n0: -12
  p0: -4
  tolerance: 0.01e-3
  ref_ch: 2
  offset:
    - -0.0
    - 0.0
  iter: 10
  rebalance : False

acbox_settings:
  chX1: 1.0
  chX2: 0.7
  chY1: 0.3
  chY2: 1.0
  frequency: 677.77
  ref_atten: 0
  sample_atten: 20

dacadc_settings:
  ch1_offset: -0.0024784313
  ch2_offset: -0.0043156862

meas_parameters:
  n0_pnts: 330
  p0_pnts: 80
  n0_rng:
    - -4.5
    - -1
  p0_rng:
    - -10
    - -2
  delta_var: 0.214285

plot: True
