# Configuration file for Capacitance Landau Fan in MLG.
# Top Gate fixed

file:
  data_dir: EMS025
  file_name: Cpen_FCI_line
  comment: Cpen, Trox = 330 mK at base (measured at 11T), rebalanced

measurement: Cbot

Ctop:
  v1: V_sample [V]
  v2: B_field [T]
  ch1: 0
  read1: 0
  read2: 1
  fixed: vt

Cbot:
  v1: V_TG [V]
  v2: B_field [T]
  ch1: 0
  read1: 0
  read2: 1
  fixed: vb

lockin: SR830  # Write 'SR830' or '7820'

lockin_settings:
  tc: 0.010
  acgain: 0
  sensitiviy: 20.0e-3

balancing_settings:
  balance_tc: 0.10
  n0: -6.1
  tolerance: 0.005e-3
  ref_ch: 2
  offset:
    - -0.0
  iter: 5
  rebalance: False

acbox_settings:
  chX1: 1.0
  chX2: 1.0
  chY1: 0.75
  chY2: 0.75
  frequency: 87564.41
  ref_atten: 26
  sample_atten: 33

dacadc_settings:
  ch1_offset: -0.0024784313
  ch2_offset: -0.0043156862

meas_parameters:
  n0_pnts: 5200
  b_pnts: 1
  n0_rng:
    - -5.6
    - 2.8
  b_rng:
    - 33.6
    - 33.6
  bscale: False
  zOffset: 0.0
  scalefactor: 1.0

plot: True
